/*
 2016/8/2 
 ZXD

Even Fibonacci numbers
Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

*/

#include <stdio.h>
#include <stdlib.h>

int main(void)
{
	int first = 1, second = 2;
	int temp;
	int sum = 0;

	while (second <= 4000000)
	{
		temp = second;
		second = first + second;
		first = temp;
		if (first % 2 == 0)
			sum += first;
	}
	printf("The result is: %d", sum);

	system("pause");
	return 0;
}